### ISSUE TITLE
Add tests for IPython Notebooks

### ISSUE THREAD

**Issue by byte-sculptor** [microsoft/MLOS#111]
At the very least we should make sure that these notebooks continue to execute without throwing exceptions. At best we validate that their output is what we expected.

We should also assert that specific notebooks are checked in with outputs.

**Comment by bpkroth** [comment]
Related #55 

@amueller to comment further on whether or not we should have the notebooks checked in with content in the repo or leave that for the webpages.

I do agree that they should be tested though, and currently we don't render/execute all of the notebooks for the webpages.

**Comment by amueller** [comment]
We can check the output, but it can be a bit tricky to get that consistent across environments unless you do really aggressive pinning (which I wouldn't suggest if we want people to use this as a library). I like having more diverse dev environments to get a little bit wider coverage of setups.
