### ISSUE TITLE
Non-option arguments to MlosAgentServer are silently ignored

### ISSUE THREAD

**Issue by amueller** [microsoft/MLOS#112]
Calling
```sh
tools/bin/dotnet out/dotnet/source/Mlos.Agent.Server/obj/AnyCPU/Mlos.Agent.Server.dll anything_at_all
```
doesn't yield an error and ``anything_at_all`` is silently ignored. I think we should error if there's anything we can't parse.

**Comment by bpkroth** [comment]
Looks like a ~~bug~~ feature:
https://github.com/commandlineparser/commandline/issues/156

**Comment by amueller** [comment]
do we have ``ignore_unknown_arguments`` True or False? From the discussion we have set it to ``False`` but it only errors on ``--`` options? I guess we can capture all the arguments and raise an error if there are any?

**Comment by bpkroth** [comment]
`ignore_unknown_arguments` defaults to `false`

Taking the later approach of capturing any ExtraArgs and throwing a warning.

Going to try and improve the usage output slightly with some examples while I'm at it.
