### ISSUE TITLE
"ListenAny" issues with Mlos.Agent.Server on Windows

### ISSUE THREAD

**Issue by bpkroth** [microsoft/MLOS#125]
We switched to ListenAny for the GrpcServer in Mlos.Agent.Server in #106 so that we could expose the ports in Docker.

Apparently this causes a security pop-up in Windows.

We should make the bind address configurable or change the default based upon a Runtime.OS platform check.

@grlap for visibility

**Comment by amueller** [comment]
I was also wondering if the current change might have security implications for the production environment?
