### ISSUE TITLE
CI pipelines for regenerating and deploying documentation website via hugo.

### ISSUE THREAD

**Issue by bpkroth** [microsoft/MLOS#19]
We should revisit hooking up documentation generation via hugo to the CI pipelines at some point.

Also documenting how to do it even if it's still manual.

_Originally posted by @bpkroth in https://github.com/microsoft/MLOS/pull/14#issuecomment-684157832_

**Comment by amueller** [comment]
I'll write proper documentation on this later, but for now the process is:

Install hugo and build the hugo part of the site:
```
sudo apt-get install hugo
cd website
./build_site.sh
rm -rf public/*
hugo
```
install sphinx and build the sphinx part of the site:
```
cd sphinx
pip install sphinx sphinx-rtd-theme numpydoc
make

Copy the sphinx part into the hugo part:
```
cp -r _build/html/ ../public/python_api
```

The easiest way to push the website that now lives in ``website/public`` to github is with
```
 git worktree add -B gh-pages website/public upstream/gh-pages
```

If a new class was added, you also need to run the sphinx source generation with
```
./apidoc.sh
```
and then reset some files with
```
git checkout .
```

easy-peasy!

**Comment by bpkroth** [comment]
@amueller this got done in #50 right?  I guess #55 is related as well.

**Comment by bpkroth** [comment]
This got started in #50.  #61 applies some additional fixups and extends it to include link checking as well.
