### ISSUE TITLE
Turn Gaussian Blob With Context into an ObjectiveFunction

### ISSUE THREAD

**Issue by byte-sculptor** [microsoft/MLOS#207]
A Gaussian Blobl is used in test_optimization_with_context right now but it's an unstable test and it's unclear why. Pulling Gaussian Blob as a separate objective function would allow us to inspect it thoroughly using the OptimizerEvaluator and all the other tools. Not to mention that it would become one of our standard workloads for the evaluation framework.

**Comment by bpkroth** [comment]
For the record, one of the goals of doing this would be to gain some confidence that the fix we applied in #206 (`n_samples = 5000`) is a good one.
