### ISSUE TITLE
mlos_bench: support for multiple VM experiments

### ISSUE THREAD

**Issue by bpkroth** [microsoft/MLOS#329]
Right now the way that Service mix-ins and config loading expectation works makes it difficult to support a single experiment that runs with multiple conflicting service types (e.g. two different providers for remote exec like ssh vs. azure) or multiple VMs (e.g. due to "vmName" being a config for the Service instead of the individual environment).  We should fix these issues to provide further flexibility in setting up experiments.

Forked off from #313

**Comment by motus** [comment]
We've fixed the issue described here in #373
