### ISSUE TITLE
Add code coverage checks

### ISSUE THREAD

**Issue by bpkroth** [microsoft/MLOS#33]
Breaking out from #6:

It would be good to add code coverage checks and badges for that to the repo landing pages.

**Comment by amueller** [comment]
using https://github.com/codecov/codecov-action
and https://www.codecov.io/ ?

**Comment by bpkroth** [comment]
That works for me.  It's what hummingbird uses as well:
https://github.com/microsoft/hummingbird/blob/b8332d12fc82c1c9137a09e69776a1555da0176a/.github/workflows/pythonapp.yml#L75

**Comment by amueller** [comment]
I wonder who recommended it to them ;)
