### ISSUE TITLE
OneShotOptimizer inconsistent treatment of tunable_values

### ISSUE THREAD

**Issue by bpkroth** [microsoft/MLOS#344]
The `OneShotOptimizer` currently supports providing
1. `include_tunable_values` which allows for a list of files with `tunable_values` to try.
2. `tunable_values` dictionary of a single set of tunable values to try.

However, the code only supports a single `tunable_value` assignment.

We should fix this to be consistent:

- either support multiple tunable values to be tried in a row (i.e. set max_iter == the `len()` tunable_values included or set in the config and rename the OneShotOptimizer to FewShotOptimizer or some such), or 
- Only allow a single tunable value in the config as well.

_Originally posted by @bpkroth in https://github.com/microsoft/MLOS/pull/340#discussion_r1189033015_

**Comment by bpkroth** [comment]
@motus maybe related to #420 ?

**Comment by motus** [comment]
Yes, since merging #420 this is a non-issue as we initialize the tunables outside of the optimizer
