### ISSUE TITLE
Custom LocalExec service config not taking precedence

### ISSUE THREAD

**Issue by bpkroth** [microsoft/MLOS#530]
- launcher.py creates a LocalExecService with a blank config:
  https://github.com/microsoft/MLOS/blob/e1120ae1565371d9203957ef61e2bb546b838e0c/mlos_bench/mlos_bench/launcher.py#L81
- this prevents environements which may specify their own `LocalExecService` config (e.g., with `temp_dir` and `abort_on_error` configs) from taking precedence)

**Comment by motus** [comment]
Leaf environments should be able to override the services that they inherit from the parent (and the Launcher). We might need to have more unit tests to verify that - and make sure that the additional services loaded in the leaf environments don't override those in the parent or siblings

**Comment by bpkroth** [comment]
As described elsewhere, there's a last writer wins problem with how we chain things.

**Comment by motus** [comment]
Fixed in #551
