### ISSUE TITLE
Add `const_args` global config replacement for Optimizer configs.

### ISSUE THREAD

**Issue by bpkroth** [microsoft/MLOS#537]
For instance:

```jsonc
// MLOS Core optimizer
{
    "$schema": "https://raw.githubusercontent.com/microsoft/MLOS/main/mlos_bench/mlos_bench/config/schemas/optimizers/optimizer-schema.json",

    "class": "mlos_bench.optimizers.MlosCoreOptimizer",

   "const_args": {
      // this can be the default
      "optimization_target": "score",
   },

    "config": {
         // and this can be replaced in the globals.jsonc config to override the default without having to provide a separate config.
        "optimization_target": "$optimization_target",
        // similar here
        "optimization_direction": "min",
        "max_iterations": 100
    }
}
```

**Comment by motus** [comment]
I don't think we need to implement it this way. We already can (and do) override the optimizer's properties just by defining them properties in some global config. For example, `optimization_target` in [`experiment_RedisBench.jsonc`](../blob/main/mlos_bench/mlos_bench/config/experiments/experiment_RedisBench.jsonc) will override the corresponding property in [`mlos_core_default_opt.jsonc`](../blob/main/mlos_bench/mlos_bench/config/optimizers/mlos_core_default_opt.jsonc). Same applies to all other configs, including Storage and Services

**Comment by bpkroth** [comment]
Yeah, that just wasn't clear initially.  Thanks for documenting.
