### ISSUE TITLE
Reliance on docker is problematic on windows machines

### ISSUE THREAD

**Issue by amueller** [microsoft/MLOS#7]
Installing docker requires windows 10 2004 which is blocked on some machines and it might be tricky to install. I didn't manage on my workstation. This might need a workaround for doing this in a teaching environment.

**Comment by markusweimer** [comment]
Docker works on older Versions of Windows which have Hyper-V installed. However, Windows Home does not include Hyper-V. Hence, the Docker setup works in the following scenarios:

  * Any current version of Windows that isn't Windows Home
  * Windows Home version 2004 or newer

That being said there is hope. The [list of update blocks for Windows 2004](https://docs.microsoft.com/en-us/windows/release-information/status-windows-10-2004) is getting shorter. Also, Microsoft [announced](https://devblogs.microsoft.com/commandline/wsl-2-support-is-coming-to-windows-10-versions-1903-and-1909/) backporting WSL2 to earlier Windows versions and [Docker has confirmed](https://www.docker.com/blog/docker-desktop-wsl-2-backport-update/) to enable Docker on those.
