### ISSUE TITLE
ConfigSpace crashes with Python 3.12

### ISSUE THREAD

**Issue by motus** [microsoft/MLOS#727]
Reproduced on Windows only so far. To reproduce, create a conda environment:
`conda create -n "p312" python=3.12 ipython ConfigSpace`
and then run:
```python
import ConfigSpace as CS
space = CS.ConfigurationSpace(seed=1234)
space.add_hyperparameter(CS.UniformFloatHyperparameter(name='x', lower=0, upper=1))
```
it will crash with
`TypeError: Expected float, got numpy.float64`

**P.S.** The issue seems to be related to [ConfigSpace issue #336](https://github.com/automl/ConfigSpace/issues/336)

**Comment by bpkroth** [comment]
Thanks so much for tracking this down.

**Comment by bpkroth** [comment]
Waiting on https://github.com/automl/ConfigSpace/pull/346 and the release that gets generated from that.
