### ISSUE TITLE
Fix issues in AzureFileShareService introduced by #779

### ISSUE THREAD

**Issue by bpkroth** [microsoft/MLOS#818]
1. `_get_share_client` is now only called once, but needs to be refreshed on demand using the `AuthService`
2. This change caused tests to try and authenticate, but we need to mock that for tests:

              Proposed fix to that:
https://github.com/motus/MLOS/pull/14

_Originally posted by @bpkroth in https://github.com/microsoft/MLOS/pull/779#discussion_r1688806116_

**Comment by motus** [comment]
Closed by #820
