### ISSUE TITLE
distutils deprecation with Python 12 preventing mlos_bench from launching

### ISSUE THREAD

**Issue by eujing** [microsoft/MLOS#865]
With docker images built on the image `python:3.12-slim`, mlos_bench (or even the storage API) now fails to run due to the deprecation of `distutils`

```
File "/root/.local/lib/python3.12/site-packages/dashboard/main.py", line 5, in <module>
from mlos_bench.storage import Storage
File "/root/.local/lib/python3.12/site-packages/mlos_bench/storage/__init__.py", line 7, in <module>
from mlos_bench.storage.base_storage import Storage
File "/root/.local/lib/python3.12/site-packages/mlos_bench/storage/base_storage.py", line 19, in <module>
from mlos_bench.storage.base_experiment_data import ExperimentData
File "/root/.local/lib/python3.12/site-packages/mlos_bench/storage/base_experiment_data.py", line 8, in <module>
from distutils.util import strtobool  # pylint: disable=deprecated-module
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'distutils'
```

The workaround is to explicitly pip install `setuptools` to provide `distutils`, but maybe we want to consider moving away from `disutils`?

**Comment by eujing** [comment]
@bpkroth @motus

**Comment by eujing** [comment]
I have not looked too deeply into the overall dependency of `disutils` yet, but if we only need `strtobool` the official implementation seems short enough to copy into the codebase.

https://github.com/python/cpython/blob/0c5fc27217525c4e40b4064e6979f467540c2fc8/Lib/distutils/util.py#L308

**Comment by bpkroth** [comment]
We test python-3.12 in the pipelines, so not sure what's different here, but I agree, we can just copy that into the one of the utils modules.
Do you want to make a PR or shall I?
